Models/ResetPassword.cs
using System.ComponentModel.DataAnnotations;

namespace ShoppingWebApp.Models
{
    public class ResetPassword
    {
        [Required]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Username must be between 2 and 20 in length!")]
        [RegularExpression(@"^[a-zA-Z0-9_]+$", ErrorMessage = "Username can only contain letters, numbers and underscores!")]
        public string Username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "New Password")]
        [StringLength(16, MinimumLength = 8, ErrorMessage = "Password must be between 8 and 16 in length!")]
        [RegularExpression(@"^[a-zA-Z0-9_]+$", ErrorMessage = "Password can only contain letters, numbers and underscores!")]
        public string NewPassword { get; set; }

        [Required(ErrorMessage = "Confirm password is required!")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("NewPassword", ErrorMessage = "Password does not match above!")]
        public string ConfirmPassword { get; set; }

        [Required]
        public string ResetCode { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using System.Windows;
using ShoppingWebApp.DB;
using ShoppingWebApp.Models;

namespace ShoppingWebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult About()
        {
            return View();
        }

        public ActionResult Index()
        {
            if (Session["User"] == null)
            {
                Session["User"] = "guest";
                Session["Cart"] = new Dictionary<int, int>();
                Session["CartQty"] = 0;
            }

            List<Product> productList = new List<Product>();
            using (ShoppingDbContext db = new ShoppingDbContext())
            {
                productList = db.Product.ToList();
            }
            ViewBag.ProductList = productList;

            return View();
        }

        public ActionResult Register()
        {
            if (Session["User"] == null || (string)Session["User"] == "member")
                return RedirectToAction("Index", "Home");

            return View();
        }

        [HttpPost]
        public ActionResult Register(Customer newCustomer)
        {
            if (newCustomer.Password != newCustomer.ConfirmPassword)
            {
                MessageBox.Show("Password and confirm password do not match!");
                return View();
            }

            if (newCustomer.Dateofbirth.Value > DateTime.Now)
            {
                MessageBox.Show("Invalid Date of Birth!");
                return View();
            }

            using (ShoppingDbContext db = new ShoppingDbContext())
            {
                Customer customer = db.Customer.Where(x => x.Username == newCustomer.Username).FirstOrDefault();
                if (customer != null)
                {
                    MessageBox.Show("Username already exists! Please choose another one.");
                    return View();
                }
                string password = newCustomer.Password;
                newCustomer.Password = Functions.ComputeSHA256(password);
                newCustomer.ConfirmPassword = null;
                newCustomer.JoinDate = DateTime.Now;
                db.Customer.Add(newCustomer);
                db.SaveChanges();
            }
            MessageBox.Show("Account successfully registered! You may now login.");

            return RedirectToAction("Login", "Home");
        }

        public ActionResult Login()
        {
            if (Session["User"] == null || (string)Session["User"] == "member")
                return RedirectToAction("Index", "Home");

            return View();
        }

        [HttpPost]
        public ActionResult Login(Customer newCustomer)
        {
            Customer customer = null;
            using (ShoppingDbContext db = new ShoppingDbContext())
            {
                customer = db.Customer.Where(x => x.Username == newCustomer.Username).FirstOrDefault();
                if (customer == null || customer.Password != Functions.ComputeSHA256(newCustomer.Password))
                {
                    MessageBox.Show("Invalid username and/or password! Please try again.");
                    return View();
                }
            }
            Session["User"] = "member";
            Session["Customer"] = customer;

            if ((string)Session["LoginType"] == "CartLogin")
                return RedirectToAction("ProcessCheckout", "Cart");

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Logout()
        {
            Session.Clear();

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Search(string searchStr)
        {
            List<Product> productList = new List<Product>();
            using (ShoppingDbContext db = new ShoppingDbContext())
            {
                if (string.IsNullOrWhiteSpace(searchStr))
                    productList = db.Product.ToList();
                else
                    productList = db.Product.Where(p => p.Name.Contains(searchStr) || p.Description.Contains(searchStr) || p.Price.ToString().Contains(searchStr)
                    || db.Category.Any(c => c.ID == p.CategoryID && c.Name.Contains(searchStr))).ToList();
            }
            ViewBag.SearchStr = searchStr;
            ViewBag.ProductList = productList;

            return PartialView("_CataloguePartialView");
        }

        public ActionResult ForgotPassword()
        {
            if (Session["User"] == null || (string)Session["User"] == "member")
                return RedirectToAction("Index", "Home");

            return View();
        }

        [HttpPost]
        public ActionResult ForgotPassword(FormCollection form)
        {
            string username = form["Username"];
            string email = form["Email"];

            string message = "";
            using (ShoppingDbContext db = new ShoppingDbContext())
            {
                Customer account = db.Customer.Where(a => a.Email == email && a.Username == username).FirstOrDefault();
                if (account != null)
                {
                    string resetCode = Guid.NewGuid().ToString();
                    SendVerificationLinkEmail(account.Email, resetCode, "ResetPassword");
                    account.ResetCode = resetCode;
                    db.SaveChanges();
                    message = "Reset password link has been sent to your email address!";
                }
                else
                    message = "Invalid username and/or email! Please try again.";
            }
            MessageBox.Show(message);

            return View();
        }

        [HttpPost]
        public void SendVerificationLinkEmail(string email, string resetCode, string emailFor = "ResetPassword")
        {
            var verifyUrl = "/Home/" + emailFor + "?id=" + resetCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);
            string subject = "";
            string body = "";

            var fromEmail = new MailAddress("Team10bca2019@gmail.com", "Team 10b");
            var toEmail = new MailAddress(email);
            var fromEmailPassword = "q1w2e3@--";

            if (emailFor == "ResetPassword")
            {
                subject = "Reset Password";
                body = "<p>Hi,</p>" +
                    "<p>We have received a request to reset your account password. Please click on the link below to reset your password.</p>" +
                    "<p><a href=" + link + ">Reset Password</a></p>" +
                    "<p>If you did not request for a password reset, then your account may have been compromised. Please login immediately and secure your account.</p>";
            }

            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
            };

            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                smtp.Send(message);
        }

        public ActionResult ResetPassword(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return HttpNotFound();

            using (ShoppingDbContext db = new ShoppingDbContext())
            {
                Customer user = db.Customer.Where(a => a.ResetCode == id).FirstOrDefault();
                if (user != null)
                {
                    ResetPassword model = new ResetPassword();
                    model.ResetCode = id;
                    model.Username = user.Username;
                    return View(model);
                }
                else
                    return HttpNotFound();
            }
        }

        [HttpPost]
        public ActionResult ResetPassword(FormCollection form)
        {
            string username = form["Username"];
            string newPassword = form["NewPassword"];

            using (ShoppingDbContext db = new ShoppingDbContext())
            {
                Customer user = db.Customer.Where(a => a.Username == username).FirstOrDefault();
                user.Password = Functions.ComputeSHA256(newPassword);
                user.ConfirmPassword = Functions.ComputeSHA256(newPassword);
                db.SaveChanges();
            }
            MessageBox.Show("Password successfully reset! You may now login.");
            Session["User"] = "guest";
            Session["Cart"] = new Dictionary<int, int>();
            Session["CartQty"] = 0;

            return RedirectToAction("Login", "Home");
        }       
    }
}

Controllers/ProfileController.cs
using System.Web.Mvc;

using ShoppingWebApp.Models;

namespace ShoppingWebApp.Controllers
{
    public class ProfileController : Controller
    {
        public ActionResult Index()
        {
            if (Session["User"] == null || (string)Session["User"] == "guest")
                return RedirectToAction("Index", "Home");

            Customer customer = (Customer)Session["Customer"];

            return View(customer);
        }
    }
}

Controllers/PurchaseController.cs
//using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;

using ShoppingWebApp.DB;
using ShoppingWebApp.Models;

namespace ShoppingWebApp.Controllers
{
    public class PurchaseController : Controller
    {
        public ActionResult Index()
        {
            if (Session["User"] == null || (string)Session["User"] == "guest")
                return RedirectToAction("Index", "Home");

            Customer customer = (Customer)Session["Customer"];
            using (ShoppingDbContext db = new ShoppingDbContext())
            {
                var grpResult = from C in db.Customer
                                from P in db.Product
                                from O in db.Order
                                from OD in db.OrderDetail
                                from ODE in db.OrderDetailExtended
                                where (C.ID == customer.ID && O.CustomerID == C.ID && OD.OrderID == O.ID && OD.ProductID == P.ID && ODE.OrderDetailID == OD.ID)
                                group ODE.ActivationCode by new { P.Name, P.Description, O.Date, OD.Quantity } into grp
                                select (new Purchase()
                                {
                                    Name = grp.Key.Name,
                                    Description = grp.Key.Description,
                                    Date = grp.Key.Date,
                                    Quantity = grp.Key.Quantity,
                                    ActivationCodes = grp.ToList()
                                });

                var orderResult = from r in grpResult
                              orderby r.Date descending, r.Name
                              select r;

                var orderResultList = orderResult.ToList();
                /*
                foreach (var grp in orderResultList)
                {
                    Debug.WriteLine("{0}, {1}, {2}, {3}", grp.Name, grp.Description, grp.Date, grp.Quantity);
                    foreach (var ac in grp.ActivationCodes)
                        Debug.WriteLine(ac);
                }
                */
                return View(orderResultList);
            }
        }
    }
}

Views/Home/About.cshtml
<h2>About <span class="blinkingAnim">Team 10b</span></h2>

Members of Team 10b:
<ul>
    <li>Keerthana Kandasamy</li>
    <li>Yuen Wei Rong, Joel</li>
    <li>Zhao Zhengyun</li>
</ul>

Views/Home/ForgotPassword.cshtml
@model ShoppingWebApp.Models.Customer

@{
    ViewBag.Title = "Request Password Reset";
}

<h2>@ViewBag.Title</h2>

<div>
    @using (Html.BeginForm("ForgotPassword", "Home", FormMethod.Post, new { autocomplete = "off" }))
    {
        <table class="login-table" align="center">
            <tr>
                <th>@Html.LabelFor(m => m.Username):</th>
                <td>@Html.EditorFor(m => m.Username, new { htmlAttributes = new { placeholder = "Enter Username...", @class = "form-control" } })</td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })</td>
                <td></td>
            </tr>
            <tr>
                <th>@Html.LabelFor(m => m.Email):</th>
                <td>@Html.EditorFor(m => m.Email, new { htmlAttributes = new { placeholder = "Enter Email...", @class = "form-control" } })</td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })</td>
                <td></td>
            </tr>
            <tr>
                <td colspan="3" align="center">
                    <button type="submit" class="btn btn-success" value="submit">
                        Submit
                    </button>
                    <p class="btn btn-warning">
                        @Html.ActionLink("Cancel", "Login", "Home", null, new { style = "text-decoration:none;" })
                    </p>
                </td>
            </tr>
        </table>
    }
</div>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Product Catalogue";
}

<h2>@ViewBag.Title</h2>


<table align="center">
    <tr>
        <td>@Html.Partial("_HeaderPartialView")</td>
        <td id="cart-view" style="text-align:center;width:110px;">@Html.Partial("_CartPartialView")</td>
    </tr>
    <tr>
        <td colspan="2">@Html.Partial("_SearchPartialView")</td>
    </tr>
    <tr>
        <td colspan="2" id="catalogue-view">@Html.Partial("_CataloguePartialView")</td>
    </tr>
</table>

Views/Home/Login.cshtml
@model ShoppingWebApp.Models.Customer

@{
    ViewBag.Title = "Login";
}

<h2>@ViewBag.Title</h2>

<div>
    @using (Html.BeginForm("Login", "Home", FormMethod.Post, new { autocomplete = "off" }))
    {
        <table class="login-table" align="center">
            <tr>
                <th>@Html.LabelFor(m => m.Username):</th>
                <td>@Html.EditorFor(m => m.Username, new { htmlAttributes = new { placeholder = "Enter Username...", @class = "form-control" } })</td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })</td>
                <td></td>
            </tr>
            <tr>
                <th>@Html.LabelFor(m => m.Password):</th>
                <td>@Html.EditorFor(m => m.Password, new { htmlAttributes = new { placeholder = "Enter Password...", @class = "form-control" } })</td>
                <td><input type="checkbox" onclick="ShowPassword(this)" />Peek</td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })</td>
                <td></td>
            </tr>
            <tr>
                <td colspan="3" align="center">
                    <button type="submit" class="btn btn-success" value="submit">
                        Login
                    </button>
                    <p class="btn btn-warning">
                        @if (Session["LoginType"] == null)
                        {
                            @Html.ActionLink("Cancel", "Index", "Home", null, new { style = "text-decoration:none;" })
                        }
                        else if ((string)Session["LoginType"] == "CartLogin")
                        {
                            @Html.ActionLink("Cancel", "Index", "Cart", null, new { style = "text-decoration:none;" })
                        }
                    </p>
                </td>
            </tr>
            <tr>
                <td colspan="3" align="center">
                    <p>Don't have an account? You can register for a new account @Html.ActionLink("here", "Register", "Home", null, new { @class = "action-link" }).</p>
                </td>
            </tr>
            <tr>
                <td colspan="3" align="center">
                    <p>Forgot your password? You can request for a password reset @Html.ActionLink("here", "ForgotPassword", "Home", null, new { @class = "action-link" }).</p>
                </td>
            </tr>
        </table>
    }
</div>

Views/Home/Register.cshtml
@model ShoppingWebApp.Models.Customer

@{
    ViewBag.Title = "Account Registration";
}

<h2>@ViewBag.Title</h2>

<div>
    @using (Html.BeginForm("Register", "Home", FormMethod.Post, new { autocomplete = "off" }))
    {
        <table class="login-table" align="center">
            <tr>
                <th>@Html.LabelFor(m => m.FirstName):</th>
                <td>@Html.EditorFor(m => m.FirstName, new { htmlAttributes = new { placeholder = "Enter First Name...", @class = "form-control" } })</td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })</td>
                <td></td>
            </tr>
            <tr>
                <th>@Html.LabelFor(m => m.LastName):</th>
                <td>@Html.EditorFor(m => m.LastName, new { htmlAttributes = new { placeholder = "Enter Last Name...", @class = "form-control" } })</td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })</td>
                <td></td>
            </tr>
            <tr>
                <th>@Html.LabelFor(m => m.Gender):</th>
                <td align="center">
                    @Html.RadioButtonFor(m => m.Gender, "M", new { id = "Male" })Male
                    &nbsp;&nbsp;
                    @Html.RadioButtonFor(m => m.Gender, "F", new { id = "Female" })Female
                </td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(m => m.Gender, "", new { @class = "text-danger" })</td>
                <td></td>
            </tr>
            <tr>
                <th>@Html.LabelFor(m => m.Username):</th>
                <td>@Html.EditorFor(m => m.Username, new { htmlAttributes = new { placeholder = "Enter Username...", @class = "form-control" } })</td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })</td>
                <td></td>
            </tr>
            <tr>
                <th>@Html.LabelFor(m => m.Password):</th>
                <td>@Html.EditorFor(m => m.Password, new { htmlAttributes = new { placeholder = "Enter Password...", @class = "form-control" } })</td>
                <td><input type="checkbox" onclick="ShowPassword(this)" />Peek</td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })</td>
                <td></td>
            </tr>
            <tr>
                <th>@Html.LabelFor(m => m.ConfirmPassword):</th>
                <td>@Html.EditorFor(m => m.ConfirmPassword, new { htmlAttributes = new { placeholder = "Confirm Password...", @class = "form-control" } })</td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th>@Html.LabelFor(m => m.Email):</th>
                <td>@Html.EditorFor(m => m.Email, new { htmlAttributes = new { placeholder = "Enter Email...", @class = "form-control" } })</td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })</td>
                <td></td>
            </tr>
            <tr>
                <th>@Html.LabelFor(m => m.Dateofbirth):</th>
                <td>@Html.EditorFor(m => m.Dateofbirth, new { htmlAttributes = new { @class = "form-control" } })</td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(m => m.Dateofbirth, "", new { @class = "text-danger" })</td>
                <td></td>
            </tr>
            <tr>
                <td colspan="3" align="center">
                    @Html.EditorFor(m => m.UserAgreement, new { @class = "form-control" })
                    I agree to Team10b's <strong>Terms of Use</strong> and <strong>Privacy Policy</strong>.
                </td>
            </tr>
            <tr>
                <td colspan="3" align="center">
                    @Html.ValidationMessageFor(m => m.UserAgreement, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td colspan="3" align="center">
                    <button type="submit" class="btn btn-success" value="submit">
                        Register
                    </button>
                    <p class="btn btn-warning">
                        @Html.ActionLink("Cancel", "Login", "Home", null, new { style = "text-decoration:none;" })
                    </p>
                </td>
            </tr>
        </table>
    }
</div>

Views/Home/ResetPassword.cshtml
@model ShoppingWebApp.Models.ResetPassword

@{
    ViewBag.Title = "Password Reset";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("ResetPassword", "Home", FormMethod.Post, new { autocomplete = "off" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        <div class="text-danger">
            @ViewBag.Message
        </div>
        <div class="success">
            @ViewBag.Message
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly"} })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { id = "Password", @class = "form-control" } })
                <input type="checkbox" onclick="ShowPassword(this)" />Peek
                @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.HiddenFor(a => a.ResetCode)
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success" value="submit">
                Submit
            </button>
            <p class="btn btn-warning">
                @Html.ActionLink("Cancel", "Index", "Home", null, new { style = "text-decoration:none;" })
            </p>
        </div>
    </div>
}

Views/Home/_CartPartialView.cshtml
@{ 
    int qty = (int)Session["CartQty"];
}

<table>
    <tr>
        <td>
            <!--@Html.ActionLink("Cart", "Index", "Cart", null, new { @class = "action-link" })-->
            <a href=@Url.Action("Index","Cart")><img src="~/img/cart.png" style="padding-bottom:5px;" height="30" width="30" /></a>
            <input class="cart-count-box" style="text-align:center;width:32px;" type="text" disabled="disabled" value="@qty">
        </td>
    </tr>
</table>

Views/Home/_CataloguePartialView.cshtml
@using ShoppingWebApp.Models;

@{
    var productList = ViewBag.ProductList as List<Product>;
}

<table>
    @if (productList.Count == 0)
    {
        <tr>
            <td>There are no products matching your search.</td>
        </tr>
    }
    else
    {
        int numOfRows = (int)Math.Ceiling((double)productList.Count / 3);
        int index = 0;
        for (int i = 0; i < 4; i++)
        {
            <tr>
                @for (int j = 0; j < 3; j++)
                {
                    <td style="text-align:center;">
                        <div class="w3-container">
                            <img src="~/img/dotnet.jpg" style="height:150px;width:150px;">
                            <p>@productList[index].Name<br></p>
                            <p>@productList[index].Description<br></p>
                            <button class="w3-button w3-black" name="@productList[index].ID" onclick="AddToCart(this)"><b>$@productList[index].Price - Add To Cart</b></button>
                        </div>
                    </td>
                    index += 1;
                    if (index >= productList.Count)
                    {
                        break;
                    }
                }
            </tr>
            if (index >= productList.Count)
            {
                break;
            }
        }
    }
</table>

Views/Home/_HeaderPartialView.cshtml
@using ShoppingWebApp.Models;

@{
    string visitor = null;
    if ((string)Session["User"] == "guest")
    {
        visitor = "Guest";
    }
    else
    {
        Customer customer = (Customer)Session["Customer"];
        visitor = customer.FirstName + " " + customer.LastName;
    }
}

<table align="center">
    <tr>
        <td>
            Hello, @visitor!
            @if (visitor == "Guest")
            {
                @Html.ActionLink("Login", "Login", "Home", null, new { @class = "action-link" })
            }
            else
            {
                @Html.ActionLink("My Profile", "Index", "Profile", null, new { @class = "action-link" })
                @:&nbsp;|&nbsp;
                @Html.ActionLink("My Purchases", "Index", "Purchase", null, new { @class = "action-link" })
                @:&nbsp;|&nbsp;
                @Html.ActionLink("Logout", "Logout", "Home", null, new { @class = "action-link", onclick = "return confirm('Confirm logout?');" })
            }
        </td>
    </tr>
</table>

Views/Home/_SearchPartialView.cshtml
@{ 
    string searchStr = ViewBag.SearchStr;
}

<table>
    <tr>
        <td class="form-group">Search:<input class="form-control" id="SearchBox" type="text" value="@searchStr" placeholder="Enter search query..." /></td>
    </tr>
</table>